import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import connectMongo from "./lib/constants/mongodb";
import { UserProvider } from "./lib/contexts/UserContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  connectMongo();
  return (
    <html lang="en">
      <body
        className={inter.className + " max-w-screen-xl mx-auto"}
        suppressHydrationWarning={true}
      >
        <UserProvider>{children}</UserProvider>
      </body>
    </html>
  );
}
